### ISSUE TITLE
Support for jsdom

### ISSUE THREAD

**Issue by mjswensen** [sbt/sbt-mocha#11]
Currently the plugin doesn't seem to play nicely with the jsdom npm module. Better support would make the plugin much more useful (already love the integration with the `test` command, pretty console output, etc.!).

Possible related issues:

* https://github.com/sbt/sbt-js-engine/issues/20
* https://github.com/playframework/playframework/issues/3565
* [This project](https://github.com/AlexanderDaniel/play-react-mocha) claims a workaround in the README, which helps to get past the phase of sbt using npm to install jsdom, but fails to run the tests (at least in my environment).

**Configurations/steps to reproduce:**

<project root>/project/plugins.sbt:

```
...
addSbtPlugin("com.typesafe.sbt" % "sbt-mocha" % "1.0.2")
...
```

<project root>/package.json:

```
{
  "devDependencies": {
    "jsdom": "^3.0.1"
  }
}
```

<project root>/test/assets/ExampleTest.js:

```
global.document = require('jsdom').jsdom();
```

As per [the aforementioned workaround](https://github.com/AlexanderDaniel/play-react-mocha), run these commands at project root:

```
rm -rf node_modules/ && npm install node-gyp && sbt web-assets:jseNpmNodeModules
```

Yields the following output:

```
Exception in thread "Trireme Script Thread" java.lang.Error: akka.pattern.AskTimeoutException: Recipient[Actor[akka://sbt-web/user/$k/stdin#1164436754]] had already been terminated.
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: akka.pattern.AskTimeoutException: Recipient[Actor[akka://sbt-web/user/$k/stdin#1164436754]] had already been terminated.
        at akka.pattern.AskableActorRef$.ask$extension(AskSupport.scala:132)
        at akka.pattern.AskableActorRef$.$qmark$extension(AskSupport.scala:144)
        at akka.contrib.process.SourceStream.getBytes(BlockingProcess.scala:310)
        at akka.contrib.process.SourceStream.read(BlockingProcess.scala:321)
        at java.io.InputStream.read(InputStream.java:170)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at io.apigee.trireme.core.internal.StreamPiper.run(StreamPiper.java:63)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        ... 2 more
[info]
[info] > contextify@0.1.11 install /Users/mjs/Projects/other/myproject/node_modules/jsdom/node_modules/contextify
[info] > node-gyp rebuild
[info]
[info]   CXX(target) Release/obj.target/contextify/src/contextify.o
[info]   SOLINK_MODULE(target) Release/contextify.node
[info]   SOLINK_MODULE(target) Release/contextify.node: Finished
[info] jsdom@3.0.1 node_modules/jsdom
[info] ├── xmlhttprequest@1.7.0
[info] ├── xml-name-validator@1.0.0
[info] ├── browser-request@0.3.3
[info] ├── cssom@0.3.0
[info] ├── nwmatcher@1.3.4
[info] ├── parse5@1.3.0
[info] ├── htmlparser2@3.8.2 (domelementtype@1.1.3, domutils@1.5.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13)
[info] ├── request@2.51.0 (caseless@0.8.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.5.0, tunnel-agent@0.4.0, node-uuid@1.4.2, qs@2.3.3, mime-types@1.0.2, combined-stream@0.0.7, tough-cookie@0.12.1, bl@0.9.4, http-signature@0.10.1, form-data@0.2.0, hawk@1.1.1)
[info] ├── cssstyle@0.2.22
[info] └── contextify@0.1.11 (bindings@1.2.1, nan@1.3.0)
[info] npm http GET https://registry.npmjs.org/jsdom/latest
[info] npm http 304 https://registry.npmjs.org/jsdom/latest
[info] npm http GET https://registry.npmjs.org/jsdom
[info] npm http 304 https://registry.npmjs.org/jsdom
[info] npm http GET https://registry.npmjs.org/jsdom/3.0.1
[info] npm http 304 https://registry.npmjs.org/jsdom/3.0.1
[info] npm http GET https://registry.npmjs.org/browser-request
[info] npm http GET https://registry.npmjs.org/contextify
[info] npm http GET https://registry.npmjs.org/cssstyle
[info] npm http GET https://registry.npmjs.org/cssom
[info] npm http GET https://registry.npmjs.org/nwmatcher
[info] npm http GET https://registry.npmjs.org/htmlparser2
[info] npm http GET https://registry.npmjs.org/parse5
[info] npm http GET https://registry.npmjs.org/request
[info] npm http GET https://registry.npmjs.org/xml-name-validator
[info] npm http GET https://registry.npmjs.org/xmlhttprequest
[info] npm http 304 https://registry.npmjs.org/nwmatcher
[info] npm http 304 https://registry.npmjs.org/htmlparser2
[info] npm http 304 https://registry.npmjs.org/cssstyle
[info] npm http 304 https://registry.npmjs.org/contextify
[info] npm http 304 https://registry.npmjs.org/browser-request
[info] npm http 304 https://registry.npmjs.org/request
[info] npm http 304 https://registry.npmjs.org/xmlhttprequest
[info] npm http 304 https://registry.npmjs.org/xml-name-validator
[info] npm http 304 https://registry.npmjs.org/parse5
[info] npm http 304 https://registry.npmjs.org/cssom
[info] npm http GET https://registry.npmjs.org/bindings
[info] npm http GET https://registry.npmjs.org/bl
[info] npm http GET https://registry.npmjs.org/forever-agent
[info] npm http GET https://registry.npmjs.org/caseless
[info] npm http GET https://registry.npmjs.org/nan
[info] npm http GET https://registry.npmjs.org/form-data
[info] npm http GET https://registry.npmjs.org/mime-types
[info] npm http GET https://registry.npmjs.org/json-stringify-safe
[info] npm http GET https://registry.npmjs.org/tunnel-agent
[info] npm http GET https://registry.npmjs.org/node-uuid
[info] npm http GET https://registry.npmjs.org/oauth-sign
[info] npm http GET https://registry.npmjs.org/qs
[info] npm http GET https://registry.npmjs.org/hawk/1.1.1
[info] npm http GET https://registry.npmjs.org/http-signature
[info] npm http GET https://registry.npmjs.org/aws-sign2
[info] npm http GET https://registry.npmjs.org/stringstream
[info] npm http GET https://registry.npmjs.org/combined-stream
[info] npm http GET https://registry.npmjs.org/tough-cookie
[info] npm http GET https://registry.npmjs.org/domhandler
[info] npm http GET https://registry.npmjs.org/domutils
[info] npm http GET https://registry.npmjs.org/domelementtype
[info] npm http GET https://registry.npmjs.org/entities
[info] npm http GET https://registry.npmjs.org/readable-stream
[info] npm http 304 https://registry.npmjs.org/forever-agent
[info] npm http 304 https://registry.npmjs.org/nan
[info] npm http 304 https://registry.npmjs.org/caseless
[info] npm http 304 https://registry.npmjs.org/bindings
[info] npm http 304 https://registry.npmjs.org/bl
[info] npm http 304 https://registry.npmjs.org/form-data
[info] npm http 304 https://registry.npmjs.org/mime-types
[info] npm http 304 https://registry.npmjs.org/json-stringify-safe
[info] npm http 304 https://registry.npmjs.org/node-uuid
[info] npm http 304 https://registry.npmjs.org/tunnel-agent
[info] npm http 304 https://registry.npmjs.org/oauth-sign
[info] npm http 304 https://registry.npmjs.org/qs
[info] npm http 304 https://registry.npmjs.org/hawk/1.1.1
[info] npm http 304 https://registry.npmjs.org/stringstream
[info] npm http 304 https://registry.npmjs.org/combined-stream
[info] npm http 304 https://registry.npmjs.org/tough-cookie
[info] npm http 304 https://registry.npmjs.org/aws-sign2
[info] npm http 304 https://registry.npmjs.org/http-signature
[info] npm http 304 https://registry.npmjs.org/domhandler
[info] npm http 304 https://registry.npmjs.org/domutils
[info] npm http 304 https://registry.npmjs.org/domelementtype
[info] npm http 304 https://registry.npmjs.org/entities
[info] npm http 304 https://registry.npmjs.org/readable-stream
[info] npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
[info] npm http GET https://registry.npmjs.org/async
[info] npm http GET https://registry.npmjs.org/ctype/0.5.3
[info] npm http GET https://registry.npmjs.org/asn1/0.1.11
[info] npm http GET https://registry.npmjs.org/assert-plus
[info] npm http GET https://registry.npmjs.org/core-util-is
[info] npm http GET https://registry.npmjs.org/isarray/0.0.1
[info] npm http GET https://registry.npmjs.org/inherits
[info] npm http GET https://registry.npmjs.org/string_decoder
[info] npm http GET https://registry.npmjs.org/punycode
[info] npm http 304 https://registry.npmjs.org/async
[info] npm http 304 https://registry.npmjs.org/core-util-is
[info] npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
[info] npm http 304 https://registry.npmjs.org/assert-plus
[info] npm http 304 https://registry.npmjs.org/isarray/0.0.1
[info] npm http 304 https://registry.npmjs.org/inherits
[info] npm http 304 https://registry.npmjs.org/string_decoder
[info] npm http 304 https://registry.npmjs.org/punycode
[info] npm http 304 https://registry.npmjs.org/asn1/0.1.11
[info] npm http GET https://registry.npmjs.org/mime-db
[info] npm http GET https://registry.npmjs.org/hoek
[info] npm http GET https://registry.npmjs.org/boom
[info] npm http GET https://registry.npmjs.org/cryptiles
[info] npm http GET https://registry.npmjs.org/sntp
[info] npm http 304 https://registry.npmjs.org/ctype/0.5.3
[info] npm http 304 https://registry.npmjs.org/sntp
[info] npm http 304 https://registry.npmjs.org/hoek
[info] npm http 304 https://registry.npmjs.org/mime-db
[info] npm http 304 https://registry.npmjs.org/boom
[info] npm http 304 https://registry.npmjs.org/cryptiles
[success] Total time: 9 s, completed Jan 20, 2015 11:47:11 PM
```

Then running `mocha` command yields the following output:

```
[error] TypeError: Cannot find function captureStackTrace in object function Error() { [native code for Error.Error, arity=1] }
[error] . (/Users/mjs/Projects/other/myproject/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js#126)     at /Users/mjs/Projects/other/myproject/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:126 (getFileName)
[error]         at /Users/mjs/Projects/other/myproject/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:55 (bindings)
[error]         at /Users/mjs/Projects/other/myproject/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:456 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:474 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:356 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:312 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:364 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:380 (require)
[error]         at /Users/mjs/Projects/other/myproject/node_modules/jsdom/lib/jsdom/browser/index.js:1 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:456 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:474 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:356 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:312 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:364 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:380 (require)
[error]         at /Users/mjs/Projects/other/myproject/node_modules/jsdom/lib/jsdom.js:10 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:456 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:474 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:356 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:312 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:364 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:380 (require)
[error]         at /Users/mjs/Projects/other/myproject/target/web/public/test/public/payment-data-test.js:38 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:456 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:474 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:356 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:312 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:364 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:380 (require)
[error]         at /Users/mjs/Projects/other/myproject/project/target/node-modules/webjars/mocha/lib/mocha.js:172 (anonymous)
[error]         at /Users/mjs/Projects/other/myproject/project/target/node-modules/webjars/mocha/lib/mocha.js:169 (anonymous)
[error]         at /Users/mjs/Projects/other/myproject/project/target/node-modules/webjars/mocha/lib/mocha.js:356 (anonymous)
[error]         at /Users/mjs/Projects/other/myproject/project/target/myproject/sbt-mocha-1.0.2.jar:128 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:456 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:474 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:356 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:312 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:497 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/main/trireme.js:141 (startup)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/main/trireme.js:872 (anonymous)
[info] so far, so good.
[trace] Stack trace suppressed: run last *:mochaExecuteTests for the full output.
[error] (*:mochaExecuteTests) com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: TypeError: Cannot find function captureStackTrace in object function Error() { [native code for Error.Error, arity=1] }
[error] . (/Users/mjs/Projects/other/myproject/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js#126)     at /Users/mjs/Projects/other/myproject/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:126 (getFileName)
[error]         at /Users/mjs/Projects/other/myproject/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:55 (bindings)
[error]         at /Users/mjs/Projects/other/myproject/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:456 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:474 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:356 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:312 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:364 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:380 (require)
[error]         at /Users/mjs/Projects/other/myproject/node_modules/jsdom/lib/jsdom/browser/index.js:1 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:456 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:474 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:356 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:312 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:364 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:380 (require)
[error]         at /Users/mjs/Projects/other/myproject/node_modules/jsdom/lib/jsdom.js:10 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:456 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:474 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:356 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:312 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:364 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:380 (require)
[error]         at /Users/mjs/Projects/other/myproject/target/web/public/test/public/payment-data-test.js:38 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:456 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:474 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:356 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:312 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:364 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:380 (require)
[error]         at /Users/mjs/Projects/other/myproject/project/target/node-modules/webjars/mocha/lib/mocha.js:172 (anonymous)
[error]         at /Users/mjs/Projects/other/myproject/project/target/node-modules/webjars/mocha/lib/mocha.js:169 (anonymous)
[error]         at /Users/mjs/Projects/other/myproject/project/target/node-modules/webjars/mocha/lib/mocha.js:356 (anonymous)
[error]         at /Users/mjs/Projects/other/myproject/project/target/myproject/sbt-mocha-1.0.2.jar:128 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:456 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:474 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:356 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:312 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:497 (anonymous)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/main/trireme.js:141 (startup)
[error]         at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/main/trireme.js:872 (anonymous)
[error] Total time: 1 s, completed Jan 20, 2015 11:49:29 PM
```

**Comment by anildigital** [comment]
@mjswensen Were you able to solve this issue?

**Comment by mjswensen** [comment]
Unfortunately not. After many hours, I ended up turning off the plugin for now. These are the issues that I believe are related:

* https://github.com/npm/npm/issues/6949
* https://github.com/sbt/sbt-mocha/issues/11

For what it's worth, here is the output of the issue I was dealing with right before removing the plugin:

    [info]
    [error] npm http GET https://registry.npmjs.org/should/latest
    [error] npm http 200 https://registry.npmjs.org/should/latest
    [error] npm ERR! 	at /Users/mjswensen/Projects/other/pedigreeable/project/target/node-modules/webjars/npm/node_modules/lockfile/lockfile.js:182 (anonymous)
    [error] npm ERR! 	at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/fs.js:107 (anonymous)
    [error] npm ERR! 	at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/main/trireme.js:805 (submitTick)
    [error] npm ERR!
    [error] npm ERR! If you need help, you may report this *entire* log,
    [error] npm ERR! including the npm and node versions, at:
    [error] npm ERR!     <http://github.com/isaacs/npm/issues>
    [error]
    [error] npm ERR! System Darwin 10.10.3
    [error] npm ERR! command "./node" "/Users/mjswensen/Projects/other/pedigreeable/project/target/node-modules/webjars/npm/lib/npm.js" "update"
    [error] npm ERR! cwd /Users/mjswensen/Projects/other/pedigreeable/.
    [error] npm ERR! node -v v0.10.24
    [error] npm ERR! npm -v 1.3.26
    [error] npm ERR!
    [error] npm ERR! Additional logging details can be found in:
    [error] npm ERR!     /Users/mjswensen/Projects/other/pedigreeable/npm-debug.log
    [error] npm ERR! not ok code 0
    [info]
    [error] npm http GET https://registry.npmjs.org/should/latest
    [error] npm http 200 https://registry.npmjs.org/should/latest
    [error] npm ERR! 	at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/fs.js:853 (anonymous)
    [error] npm ERR! 	at /Users/mjswensen/Projects/other/pedigreeable/project/target/node-modules/webjars/npm/node_modules/graceful-fs/polyfills.js:131 (anonymous)
    [error] npm ERR! 	at /Users/mjswensen/Projects/other/pedigreeable/project/target/node-modules/webjars/npm/node_modules/chownr/chownr.js:12 (anonymous)
    [error] npm ERR! 	at /Users/mjswensen/Projects/other/pedigreeable/project/target/node-modules/webjars/npm/node_modules/graceful-fs/graceful-fs.js:142 (anonymous)
    [error] npm ERR! 	at /Users/mjswensen/Projects/other/pedigreeable/project/target/node-modules/webjars/npm/node_modules/graceful-fs/graceful-fs.js:89 (anonymous)
    [error] npm ERR! 	at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/fs.js:107 (anonymous)
    [error] npm ERR! 	at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/main/trireme.js:805 (submitTick)
    [error] npm ERR!
    [error] npm ERR! If you need help, you may report this *entire* log,
    [error] npm ERR! including the npm and node versions, at:
    [error] npm ERR!     <http://github.com/isaacs/npm/issues>
    [error]
    [error] npm ERR! System Darwin 10.10.3
    [error] npm ERR! command "./node" "/Users/mjswensen/Projects/other/pedigreeable/project/target/node-modules/webjars/npm/lib/npm.js" "update"
    [error] npm ERR! cwd /Users/mjswensen/Projects/other/pedigreeable/.
    [error] npm ERR! node -v v0.10.24
    [error] npm ERR! npm -v 1.3.26
    [error] npm ERR!
    [error] npm ERR! Additional logging details can be found in:
    [error] npm ERR!     /Users/mjswensen/Projects/other/pedigreeable/npm-debug.log
    [error] npm ERR! not ok code 0
    [trace] Stack trace suppressed: run last web-assets:jseNpmNodeModules for the full output.
    [trace] Stack trace suppressed: run last web-assets-test:jseNpmNodeModules for the full output.
    [error] (web-assets:jseNpmNodeModules) Problems with NPM resolution. Aborting build.
    [error] (web-assets-test:jseNpmNodeModules) Problems with NPM resolution. Aborting build.
    [error] Total time: 7 s, completed Jun 20, 2015 4:36:36 PM

I think part of the issue is due to the plugin using a very outdated version of npm.

**Comment by benmccann** [comment]
I believe that this is fixed with the latest version of sbt-js-engine. Sent a PR to upgrade here: https://github.com/sbt/sbt-mocha/pull/16

**Comment by LeonhardtDavid** [comment]
Could it be possible to merge PR #16 ? A year and still pending, it would be very helpfull for us and many others that are getting the same error.

**Comment by benmccann** [comment]
Merged. You'll have to ask someone else to cut a new release though

**Comment by LeonhardtDavid** [comment]
That's great! Thank you @benmccann !
Do you know who manage the releases?

**Comment by huntc** [comment]
@benmccann I believe that you do have publishing rights... Let me know if there are issues. Check out sbt-less for its build.sbt in case this one needs updating wrt publishing etc. I can do this on Monday if it looks a bit tricky.

**Comment by benmccann** [comment]
@huntc are there publishing instructions anywhere? last time i tried i was supposed to have rights, but it still didn't work for me

**Comment by huntc** [comment]
Er - no - we use sbt-release. I'll tackle this on Monday and I'll be sure to forward you some notes. Cheers.

**Comment by LeonhardtDavid** [comment]
Thanks @benmccann and @huntc !

**Comment by todd-cook** [comment]
Is the release still pending or hung up?

Hope to see it soon!

thanks
